### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by JeremieD**
I finished the icons and the theme file, then packaged everything up in a zip.
I also added a little bit of blue in the UI. I'm not sure if I like it. Tell me if you prefer just white.

### CODE REVIEW

**Comment by davelab6** [comment]
You can commit here yourself if you wish :)

**Comment by davelab6** [comment]
Ah, the license should be the same as FontForge itself, GPLv3 

Also the ZIP can be done via a 'git tag' and then github's Releases page will make the zip of the git repo at that point. 

Also, www.semver.org could be used for version numbering :)

**Comment by jjjejjj** [comment]
I'm sorry, I'm quite new to Git and GitHub :D
Thank you for your collaboration though, I'll look into the licence and version numbering for a future release.

**Comment by davelab6** [comment]
All good :)

**Pull request merged**
